version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the id of the order
          - name: products_id
            description: id of the products
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns: 
          - name: products_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipment costs info by orders id. 
        columns: 
          - name: orders_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee for every order
          - name: logcost
            description: logcosts for every order
          - name: ship_cost
            description: shipcosts for every order
      - name: adwords
        identifier: raw_gz_adwords
        description: spent on adwords
        tests:
              - unique:
                  column_name: "(campaign_key || '-'|| date_date)"
              - not_null:
                  column_name:
                    - paid_soure
                    - campaign_name
        columns: 
          - name: date_date
            description: the date
          - name: paid_source
            description: equals name
          - name: campaign_key
            description: campaign_key, not primary key
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of ads
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: bing
        identifier: raw_gz_bing
        description: spent on bing
        tests:
              - unique:
                  column_name: "(campaign_key || '-'|| date_date)"
              - not_null:
                  column_name:
                    - paid_soure
                    - campaign_name
        columns: 
          - name: date_date
            description: the date
          - name: paid_source
            description: equals name
          - name: campaign_key
            description: campaign_key, not primary key
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of ads
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: spent on criteo
        tests:
              - unique:
                  column_name: "(campaign_key || '-'|| date_date)"
              - not_null:
                  column_name:
                    - paid_soure
                    - campaign_name
        columns: 
          - name: date_date
            description: the date
          - name: paid_source
            description: equals name
          - name: campaign_key
            description: campaign_key, not primary key
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of ads
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: spent on facebook
        tests:
              - unique:
                  column_name: "(campaign_key || '-'|| date_date)"
              - not_null:
                  column_name:
                    - paid_soure
                    - campaign_name
        columns: 
          - name: date_date
            description: the date
          - name: paid_source
            description: equals name
          - name: campaign_key
            description: campaign_key, not primary key
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of ads
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks

models:
      - name: int_orders_margin
        columns:
          - name: orders_id
            description: Primary key of the table orders margin
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
      - name: int_orders_operational
        columns:
          - name: orders_id
            description: Primary key of the table operational
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
          - name: operational_margin
            description: not null
            tests:
              - not_null
      - name: int_sales_margin
        columns:
          - name: "(orders_id || '-' || products_id)"
            description: primary key
            tests:
              - unique 
              - not_null 
          - name: revenue
            description: revenue not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
      - name: finance_days
        columns:
          - name: date_date
            description: Primary key of the table finance day
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
          - name: operational_margin
            description: not null
            tests:
              - not_null
          - name: average_basket
            description: not null
            tests:
              - not_null
      - name: int_campaigns
        tests:
              - unique:
                  column_name: "(campaign_key || '-'|| date_date)"
              - not_null:
                  column_name:
                    - paid_soure
                    - campaign_name
                    - campaign_key
                    - ads_cost
                    - impression
                    - click
      - name: int_campaigns_day
        columns:
          - name: date_date
            description: Primary key of the table campaigns per day
            tests:
              - unique
              - not_null
          - name: ads_cost
            description: total of cost for the ads for that day
            tests:
              - not_null
          - name: ads_impression
            description: total of impressions of the ads for that day
            tests:
              - not_null
          - name: ads_click
            description: total of clicks of the ads for that day
            tests:
              - not_null
      - name: finance_campaigns_day
        columns:
          - name: date_date
            description: Primary key of the table campaigns per day
            tests:
              - unique
              - not_null
          - name: ads_margin
            description: total of margin for the ads for that day (operation margin minus ads cost)
          - name: average_basket
            description: total average basket for that day
          - name: operational_margin
            description: total operational margin for that day
          - name: ads_cost
            description: total of cost for the ads for that day


