version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the id of the order
          - name: products_id
            description: id of the products
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns: 
          - name: products_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipment costs info by orders id. 
        columns: 
          - name: orders_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee for every order
          - name: logcost
            description: logcosts for every order
          - name: ship_cost
            description: shipcosts for every order
      - name: adwords
        identifier: raw_gz_adwords
        description: spent on adwords
        columns:
          - name: date_date
            description: the date
            tests:
              - not_null
          - name: paid_source
            description: name of source 
            tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
            tests:
              - not_null 
          - name: ads_cost
            description: costs of ad
            tests:
              - not_null
          - name: impression
            description: number of views of the ad
            tests:
              - not_null
          - name: click
            description: number of clicks on the ad
            tests:
              - not_null
      - name: bing
        identifier: raw_gz_bing
        description: spent on bing
        columns:
          - name: date_date
            description: the date
            tests:
              - not_null
          - name: paid_source
            description: name of source 
            tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
            tests:
              - not_null 
          - name: ads_cost
            description: costs of ad
            tests:
              - not_null
          - name: impression
            description: number of views of the ad
            tests:
              - not_null
          - name: click
            description: number of clicks on the ad
            tests:
              - not_null


models:
      - name: int_orders_margin
        columns:
          - name: orders_id
            description: Primary key of the table orders margin
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
      - name: int_orders_operational
        columns:
          - name: orders_id
            description: Primary key of the table operational
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
          - name: operational_margin
            description: not null
            tests:
              - not_null
      - name: int_sales_margin
        columns:
          - name: "(orders_id || '-' || products_id)"
            description: primary key
            tests:
              - unique 
              - not_null 
          - name: revenue
            description: revenue not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
      - name: finance_days
        columns:
          - name: date_date
            description: Primary key of the table finance day
            tests:
              - unique
              - not_null
          - name: revenue
            description: not null
            tests:
              - not_null
          - name: margin
            description: not null
            tests:
              - not_null
          - name: operational_margin
            description: not null
            tests:
              - not_null
          - name: average_basket
            description: not null
            tests:
              - not_null
